name: cheese-paper ci build and publish

on:
  push:
    branches:
      - '**'

# allow concurrent builds, but only one build per pull request
# from ziglang: https://codeberg.org/ziglang/zig/src/commit/0e3c6514a4d1f89498bf411b58131d129218807f/.forgejo/workflows/ci.yaml#L10-L14
concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.event.pull_request.number || forgejo.sha }}
  cancel-in-progress: ${{ forgejo.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  # hacky fix to make linking work properly on macos build hosts,
  # I'm not sure exactly what's stopping it from working normally
  RUSTFLAGS: "-L native=/opt/homebrew/opt/llvm/lib/"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-x86_64
            name: linux-x86_64
            build_name: cheese-paper
            archive_name: cheese-paper
          - os: windows-x86_64
            name: windows.exe
            build_name: cheese-paper.exe
            archive_name: cheese-paper.exe
          - os: macos-arm64
            name: macos.app.zip
            build_name: bundle/osx/cheese-paper.app
            archive_name: bundle/osx/cheese-paper.app.zip

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Create app bundle
      if: runner.os == 'macOS'
      shell: bash
      run: |
        cargo install cargo-bundle
        cargo bundle --release
        zip -r target/release/${{ matrix.archive_name }} target/release/${{ matrix.build_name }}
    - name: Upload Artifacts
      # we don't need/want to upload binaries on pull requests, but doing everything
      # else is good
      if: forgejo.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: cheese-paper-${{ matrix.name }}
        path: target/release/${{ matrix.archive_name }}
