name: cheese-paper release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: linux-x86_64

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Get the release version from the tag
      run: echo "VERSION=${{ forgejo.ref_name }}" >> $FORGEJO_ENV
    - name: Get the Cargo.toml version
      shell: bash
      run: echo "CARGO_TOML_VERSION=$(cargo pkgid | awk -F'[#@]' '{print $NF}')" >> $FORGEJO_ENV
    - name: Compare the version in cargo.toml to the tag
      if: ${{ forgejo.ref_name != env.CARGO_TOML_VERSION }}
      run: echo "ref name '${{ forgejo.ref_name }}' does not match cargo toml version '${{ env.CARGO_TOML_VERSION }}'"; exit 1
    - name: publish release
      shell: bash
      # if the tag already exists, we accept that as a success for the job, allowing re-runs of the entire release
      run: |
        curl -X 'GET' \
          'https://codeberg.org/api/v1/repos/${{ forgejo.repository }}/releases/tags/${{ forgejo.ref_name }}' --no-progress-meter \
          --fail-with-body -H 'accept: application/json' || \
        curl -X 'POST' \
          'https://codeberg.org/api/v1/repos/${{ forgejo.repository }}/releases' \
          --fail-with-body \
          -H 'accept: application/json' \
          -H 'Authorization: token ${{ forgejo.token }}' \
          -H 'Content-Type: application/json' \
          -d '{
          "name": "${{ forgejo.ref_name }}",
          "tag_name": "${{ forgejo.ref_name }}",
          "draft": true,
          "target_commitish": "${{ forgejo.ref_name }}"
        }'

  build-and-create-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-x86_64
            name: cheese-paper-linux-x86_64
            build_name: cheese-paper
            archive_name: cheese-paper
          - os: windows-x86_64
            name: cheese-paper-windows.exe
            build_name: cheese-paper.exe
            archive_name: cheese-paper.exe
          - os: macos-arm64
            name: cheese-paper-macos-arm64.app.zip
            build_name: bundle/osx/cheese-paper.app
            archive_name: bundle/osx/cheese-paper.app.zip

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Create app bundle
      if: runner.os == 'macOS'
      shell: bash
      run: |
        cargo install cargo-bundle
        cargo bundle --release
        zip -r target/release/${{ matrix.archive_name }} target/release/${{ matrix.build_name }}

    - name: Upload artifacts to release
      shell: bash
      run: |
        # find python version. we need to use python3 on macos and python on windows :)
        export PYTHON_BINARY=$(if [[ $(python -V) ]]; then echo "python"; else echo "python3"; fi)
        # find the id of the release we created above
        export RELEASE_ID=$(curl -X 'GET' \
          'https://codeberg.org/api/v1/repos/${{ forgejo.repository }}/releases/tags/${{ forgejo.ref_name }}' \
          --no-progress-meter --fail-with-body \
          -H 'Authorization: token ${{ forgejo.token }}' \
          -H 'accept: application/json' | ${PYTHON_BINARY} -c 'import json,sys; print(json.load(sys.stdin)["id"])')

        echo "release id: ${RELEASE_ID}"

        curl -X 'POST' \
          "https://codeberg.org/api/v1/repos/${{ forgejo.repository }}/releases/${RELEASE_ID}/assets?name=${{ matrix.name }}" \
          --fail-with-body --no-progress-meter \
          -H 'accept: application/json' \
          -H 'Authorization: token ${{ forgejo.token }}' \
          -H 'Content-Type: multipart/form-data' \
          -F 'attachment=@target/release/${{ matrix.archive_name }};type=application/octet-stream'

